-- 插入缺失的币种数据
INSERT INTO system_currency (currency_code, name, symbol, deleted, create_time, update_time) VALUES
('BRL', '巴西雷亚尔', 'R$', b'0', NOW(), NOW()),
('CHF', '瑞士法郎', 'Fr', b'0', NOW(), NOW()),
('CZK', '捷克克朗', 'Kč', b'0', NOW(), NOW()),
('DKK', '丹麦克朗', 'kr', b'0', NOW(), NOW()),
('HKD', '港币', 'HK$', b'0', NOW(), NOW()),
('HUF', '匈牙利福林', 'Ft', b'0', NOW(), NOW()),
('IDR', '印尼卢比', 'Rp', b'0', NOW(), NOW()),
('ILS', '以色列新谢克尔', '₪', b'0', NOW(), NOW()),
('INR', '印度卢比', '₹', b'0', NOW(), NOW()),
('ISK', '冰岛克朗', 'kr', b'0', NOW(), NOW()),
('MXN', '墨西哥比索', 'MX$', b'0', NOW(), NOW()),
('MYR', '马来西亚林吉特', 'RM', b'0', NOW(), NOW()),
('NOK', '挪威克朗', 'kr', b'0', NOW(), NOW()),
('NZD', '新西兰元', 'NZ$', b'0', NOW(), NOW()),
('PHP', '菲律宾比索', '₱', b'0', NOW(), NOW()),
('PLN', '波兰兹罗提', 'zł', b'0', NOW(), NOW()),
('RON', '罗马尼亚列伊', 'lei', b'0', NOW(), NOW()),
('SEK', '瑞典克朗', 'kr', b'0', NOW(), NOW()),
('SGD', '新加坡元', 'S$', b'0', NOW(), NOW()),
('THB', '泰铢', '฿', b'0', NOW(), NOW()),
('TRY', '土耳其里拉', '₺', b'0', NOW(), NOW()),
('ZAR', '南非兰特', 'R', b'0', NOW(), NOW());
